name: app

on:
  push:
    branches: [main]
    paths:
      - app/**
      - .github/workflows/app.yml
  pull_request:
    branches: [main]
    paths:
      - app/**
      - .github/workflows/app.yml

jobs:
  ts:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: app/package-lock.json
      - run: npm install
      - run: npm run lint
      - run: npm run build
